const allMusicInfo = [
    {
        artist: "Burna Boy",
        songName: "Level Up(Twice as Tall)",
        album: "Twice as Tall - 2020",
        songImage: "https://theartsdesk.com/sites/default/files/mastimages/burna-boy-twice-as-tall.jpg",
        songLink: "music/Burna boy - Twice as Tall/01-Burna-Boy-Level-Up-Twice-As-Tall-ft-Youssou-N-Dour-360media.com_.ng_.mp3",
    },
    {
        artist: "2 baba",
        songName: "African Queen",
        album: "Single - 2000",
        songImage: "music/2face/2face African QUEEN.png",
        songLink: "music/2face/2Face Idibia - African Queen.mp3",
    },
    {
        artist: "Abracadabra",
        songName: "On Deck",
        album: "On Deck / Abracadabra Freestyle - 2020",
        songImage: "music/Ab - on deck/Abra-Cadabra-On-Deck.jpg",
        songLink: "music/Ab - on deck/Abra_Cadabra_Ft_RV_Kush_Double_Lz_Bandokay_Lowkey_Dezzie_-_On_Deck_Remix_ - Copy.mp3",
    },
    // {
    //     artist: "Burna Boy",
    //     songName: "Level Up(Twice as Tall)",
    //     album: "Twice as Tall",
    //     songImage: "music/Burna boy - Twice as Tall/Twice_as_Tall_Burna_Boy_Album.jpg",
    //     songLink: "music/Burna boy - Twice as Tall/01-Burna-Boy-Level-Up-Twice-As-Tall-ft-Youssou-N-Dour-360media.com_.ng_.mp3",
    // },
    {
        artist: "J Cole",
        songName: "MIDDLE CHILD",
        album: "Single - 2019",
        songImage: "music/J cole - middle child/J._Cole_-_Middle_Child.png",
        songLink: "music/J cole - middle child/J._Cole_-_Middle_Child.png",
    },
    {
        artist: "Koffee",
        songImage: "music/koffe - toast/toast.jpg",
        songName: "Toast",
        album: "Rapture - 2019",
        songLink: "music/koffe - toast/Koffee - Toast (Official Video).mp3",
    },
    {
        artist: "Omah Lay",
        songName: "Godly",
        album: "What Have We Done-EP - 2020",
        songImage: "music/Omah lay - Godly/Omah-Lay-What-Have-We-Done-EP.jpg",
        songLink: "music/Omah lay - Godly/03 Omah Lay - Godly (NetNaija.com).mp3",
    },
    {
        artist: "Roddy Ricch",
        songName: "Die Young",
        album: "Single - 2018",
        songImage: "music/roddy/Roddy_Ricch_-_Die_Young.jpg",
        songLink: "music/roddy/04. Die Young.mp3",
    },
    {
        artist: "Ruger",
        songName: "Ruger",
        album: "Pandemic-EP - 2021",
        songImage: "music/Ruger - bounce/Ruger-Bounce.jpg",
        songLink: "music/Ruger - bounce/05-Ruger-Bounce-(JustNaija.com).mp3",
    },
    {
        artist: "6LACK",
        songName: "Pretty Little Fears (ft. J Cole)",
        album: "East Atlanta Love Letter - 2021",
        songImage: "music/6lack/pretyy little fears.png",
        songLink: "music/6lack/6LACK_-_Pretty_Little_Fears_ft_J_Cole.mp3",
    },
    {
        artist: "Burna Boy",
        songName: "Ye",
        album: "Outside - 2018",
        songImage: "music/Burna boy - Ye/ye.jpg",
        songLink: "music/Burna boy - Ye/06 . Burna Boy - Ye.mp3",
    }
]